// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/models/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MoexClient is an autogenerated mock type for the MoexClient type
type MoexClient struct {
	mock.Mock
}

// GetSpecifications provides a mock function with given fields: ctx, ticker, date
func (_m *MoexClient) GetSpecifications(ctx context.Context, ticker string, date time.Time) (domain.ValuesMoex, error) {
	ret := _m.Called(ctx, ticker, date)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecifications")
	}

	var r0 domain.ValuesMoex
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (domain.ValuesMoex, error)); ok {
		return rf(ctx, ticker, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) domain.ValuesMoex); ok {
		r0 = rf(ctx, ticker, date)
	} else {
		r0 = ret.Get(0).(domain.ValuesMoex)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, ticker, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMoexClient creates a new instance of MoexClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoexClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MoexClient {
	mock := &MoexClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
