// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	url "net/url"

	mock "github.com/stretchr/testify/mock"
)

// HTTPTransport is an autogenerated mock type for the HTTPTransport type
type HTTPTransport struct {
	mock.Mock
}

// DoRequest provides a mock function with given fields: ctx, Path, query
func (_m *HTTPTransport) DoRequest(ctx context.Context, Path string, query url.Values) ([]byte, error) {
	ret := _m.Called(ctx, Path, query)

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) ([]byte, error)); ok {
		return rf(ctx, Path, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) []byte); ok {
		r0 = rf(ctx, Path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values) error); ok {
		r1 = rf(ctx, Path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHTTPTransport creates a new instance of HTTPTransport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPTransport(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPTransport {
	mock := &HTTPTransport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
