// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/models/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	service_models "bonds-report-service/internal/service/service_models"

	time "time"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CloseDB provides a mock function with no fields
func (_m *Storage) CloseDB() {
	_m.Called()
}

// DeleteBondReport provides a mock function with given fields: ctx, chatID, accountId
func (_m *Storage) DeleteBondReport(ctx context.Context, chatID int, accountId string) error {
	ret := _m.Called(ctx, chatID, accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBondReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, chatID, accountId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteGeneralBondReport provides a mock function with given fields: ctx, chatID, accountId
func (_m *Storage) DeleteGeneralBondReport(ctx context.Context, chatID int, accountId string) error {
	ret := _m.Called(ctx, chatID, accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGeneralBondReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, chatID, accountId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrency provides a mock function with given fields: ctx, currency, date
func (_m *Storage) GetCurrency(ctx context.Context, currency string, date time.Time) (float64, error) {
	ret := _m.Called(ctx, currency, date)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrency")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (float64, error)); ok {
		return rf(ctx, currency, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) float64); ok {
		r0 = rf(ctx, currency, date)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, currency, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperations provides a mock function with given fields: ctx, chatId, assetUid, accountId
func (_m *Storage) GetOperations(ctx context.Context, chatId int, assetUid string, accountId string) ([]domain.OperationWithoutCustomTypes, error) {
	ret := _m.Called(ctx, chatId, assetUid, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetOperations")
	}

	var r0 []domain.OperationWithoutCustomTypes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) ([]domain.OperationWithoutCustomTypes, error)); ok {
		return rf(ctx, chatId, assetUid, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) []domain.OperationWithoutCustomTypes); ok {
		r0 = rf(ctx, chatId, assetUid, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OperationWithoutCustomTypes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, chatId, assetUid, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUid provides a mock function with given fields: ctx, instrumentUid
func (_m *Storage) GetUid(ctx context.Context, instrumentUid string) (string, error) {
	ret := _m.Called(ctx, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetUid")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, instrumentUid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsUpdatedUids provides a mock function with given fields: ctx
func (_m *Storage) IsUpdatedUids(ctx context.Context) (time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsUpdatedUids")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LastOperationTime provides a mock function with given fields: ctx, chatID, accountId
func (_m *Storage) LastOperationTime(ctx context.Context, chatID int, accountId string) (time.Time, error) {
	ret := _m.Called(ctx, chatID, accountId)

	if len(ret) == 0 {
		panic("no return value specified for LastOperationTime")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (time.Time, error)); ok {
		return rf(ctx, chatID, accountId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) time.Time); ok {
		r0 = rf(ctx, chatID, accountId)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, chatID, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBondReport provides a mock function with given fields: ctx, chatID, accountId, bondReport
func (_m *Storage) SaveBondReport(ctx context.Context, chatID int, accountId string, bondReport []service_models.BondReport) error {
	ret := _m.Called(ctx, chatID, accountId, bondReport)

	if len(ret) == 0 {
		panic("no return value specified for SaveBondReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, []service_models.BondReport) error); ok {
		r0 = rf(ctx, chatID, accountId, bondReport)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveCurrency provides a mock function with given fields: ctx, currencies, date
func (_m *Storage) SaveCurrency(ctx context.Context, currencies domain.CurrenciesCBR, date time.Time) error {
	ret := _m.Called(ctx, currencies, date)

	if len(ret) == 0 {
		panic("no return value specified for SaveCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CurrenciesCBR, time.Time) error); ok {
		r0 = rf(ctx, currencies, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveGeneralBondReport provides a mock function with given fields: ctx, chatID, accountId, bondReport
func (_m *Storage) SaveGeneralBondReport(ctx context.Context, chatID int, accountId string, bondReport []service_models.GeneralBondReportPosition) error {
	ret := _m.Called(ctx, chatID, accountId, bondReport)

	if len(ret) == 0 {
		panic("no return value specified for SaveGeneralBondReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, []service_models.GeneralBondReportPosition) error); ok {
		r0 = rf(ctx, chatID, accountId, bondReport)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveOperations provides a mock function with given fields: ctx, chatID, accountId, operations
func (_m *Storage) SaveOperations(ctx context.Context, chatID int, accountId string, operations []domain.OperationWithoutCustomTypes) error {
	ret := _m.Called(ctx, chatID, accountId, operations)

	if len(ret) == 0 {
		panic("no return value specified for SaveOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, []domain.OperationWithoutCustomTypes) error); ok {
		r0 = rf(ctx, chatID, accountId, operations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUids provides a mock function with given fields: ctx, uids
func (_m *Storage) SaveUids(ctx context.Context, uids map[string]string) error {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for SaveUids")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) error); ok {
		r0 = rf(ctx, uids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
