// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	generalbondreport "bonds-report-service/internal/domain/generalbondreport"
	context "context"

	mock "github.com/stretchr/testify/mock"

	report "bonds-report-service/internal/domain/report_position"

	time "time"
)

// GeneralBondReportProcessor is an autogenerated mock type for the GeneralBondReportProcessor type
type GeneralBondReportProcessor struct {
	mock.Mock
}

// GetGeneralBondReportPosition provides a mock function with given fields: ctx, currentPositions, totalAmount, moexBuyDateData, moexNowData, firstBondsBuyDate
func (_m *GeneralBondReportProcessor) GetGeneralBondReportPosition(ctx context.Context, currentPositions []report.PositionByFIFO, totalAmount float64, moexBuyDateData domain.ValuesMoex, moexNowData domain.ValuesMoex, firstBondsBuyDate time.Time) (generalbondreport.GeneralBondReportPosition, error) {
	ret := _m.Called(ctx, currentPositions, totalAmount, moexBuyDateData, moexNowData, firstBondsBuyDate)

	if len(ret) == 0 {
		panic("no return value specified for GetGeneralBondReportPosition")
	}

	var r0 generalbondreport.GeneralBondReportPosition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []report.PositionByFIFO, float64, domain.ValuesMoex, domain.ValuesMoex, time.Time) (generalbondreport.GeneralBondReportPosition, error)); ok {
		return rf(ctx, currentPositions, totalAmount, moexBuyDateData, moexNowData, firstBondsBuyDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []report.PositionByFIFO, float64, domain.ValuesMoex, domain.ValuesMoex, time.Time) generalbondreport.GeneralBondReportPosition); ok {
		r0 = rf(ctx, currentPositions, totalAmount, moexBuyDateData, moexNowData, firstBondsBuyDate)
	} else {
		r0 = ret.Get(0).(generalbondreport.GeneralBondReportPosition)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []report.PositionByFIFO, float64, domain.ValuesMoex, domain.ValuesMoex, time.Time) error); ok {
		r1 = rf(ctx, currentPositions, totalAmount, moexBuyDateData, moexNowData, firstBondsBuyDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGeneralBondReportProcessor creates a new instance of GeneralBondReportProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeneralBondReportProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeneralBondReportProcessor {
	mock := &GeneralBondReportProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
