// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	domainreport "bonds-report-service/internal/domain/report"
	context "context"

	mock "github.com/stretchr/testify/mock"

	report "bonds-report-service/internal/domain/report_position"
)

// BondReportProcessor is an autogenerated mock type for the BondReportProcessor type
type BondReportProcessor struct {
	mock.Mock
}

// CreateBondReport provides a mock function with given fields: ctx, currentPositions, moexBuyDateData, moexNowData
func (_m *BondReportProcessor) CreateBondReport(ctx context.Context, currentPositions []report.PositionByFIFO, moexBuyDateData domain.ValuesMoex, moexNowData domain.ValuesMoex) (domainreport.Report, error) {
	ret := _m.Called(ctx, currentPositions, moexBuyDateData, moexNowData)

	if len(ret) == 0 {
		panic("no return value specified for CreateBondReport")
	}

	var r0 domainreport.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []report.PositionByFIFO, domain.ValuesMoex, domain.ValuesMoex) (domainreport.Report, error)); ok {
		return rf(ctx, currentPositions, moexBuyDateData, moexNowData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []report.PositionByFIFO, domain.ValuesMoex, domain.ValuesMoex) domainreport.Report); ok {
		r0 = rf(ctx, currentPositions, moexBuyDateData, moexNowData)
	} else {
		r0 = ret.Get(0).(domainreport.Report)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []report.PositionByFIFO, domain.ValuesMoex, domain.ValuesMoex) error); ok {
		r1 = rf(ctx, currentPositions, moexBuyDateData, moexNowData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBondReportProcessor creates a new instance of BondReportProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBondReportProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *BondReportProcessor {
	mock := &BondReportProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
