// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CbrCurrencyGetter is an autogenerated mock type for the CbrCurrencyGetter type
type CbrCurrencyGetter struct {
	mock.Mock
}

// GetCurrencyFromCB provides a mock function with given fields: ctx, charCode, date
func (_m *CbrCurrencyGetter) GetCurrencyFromCB(ctx context.Context, charCode string, date time.Time) (float64, error) {
	ret := _m.Called(ctx, charCode, date)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyFromCB")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (float64, error)); ok {
		return rf(ctx, charCode, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) float64); ok {
		r0 = rf(ctx, charCode, date)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, charCode, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCbrCurrencyGetter creates a new instance of CbrCurrencyGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCbrCurrencyGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CbrCurrencyGetter {
	mock := &CbrCurrencyGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
