// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DividerByAssetType is an autogenerated mock type for the DividerByAssetType type
type DividerByAssetType struct {
	mock.Mock
}

// DivideByType provides a mock function with given fields: ctx, positions
func (_m *DividerByAssetType) DivideByType(ctx context.Context, positions []domain.PortfolioPosition) (*domain.PortfolioByTypeAndCurrency, error) {
	ret := _m.Called(ctx, positions)

	if len(ret) == 0 {
		panic("no return value specified for DivideByType")
	}

	var r0 *domain.PortfolioByTypeAndCurrency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.PortfolioPosition) (*domain.PortfolioByTypeAndCurrency, error)); ok {
		return rf(ctx, positions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.PortfolioPosition) *domain.PortfolioByTypeAndCurrency); ok {
		r0 = rf(ctx, positions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PortfolioByTypeAndCurrency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.PortfolioPosition) error); ok {
		r1 = rf(ctx, positions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDividerByAssetType creates a new instance of DividerByAssetType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDividerByAssetType(t interface {
	mock.TestingT
	Cleanup(func())
}) *DividerByAssetType {
	mock := &DividerByAssetType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
