// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OperationsUpdater is an autogenerated mock type for the OperationsUpdater type
type OperationsUpdater struct {
	mock.Mock
}

// UpdateOperations provides a mock function with given fields: ctx, chatID, accountID, openDate
func (_m *OperationsUpdater) UpdateOperations(ctx context.Context, chatID int, accountID string, openDate time.Time) error {
	ret := _m.Called(ctx, chatID, accountID, openDate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, time.Time) error); ok {
		r0 = rf(ctx, chatID, accountID, openDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOperationsUpdater creates a new instance of OperationsUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationsUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationsUpdater {
	mock := &OperationsUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
