// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PositionProcessor is an autogenerated mock type for the PositionProcessor type
type PositionProcessor struct {
	mock.Mock
}

// ProcessPositionsToPositionsWithAssetUid provides a mock function with given fields: ctx, portffolioPositions
func (_m *PositionProcessor) ProcessPositionsToPositionsWithAssetUid(ctx context.Context, portffolioPositions []domain.PortfolioPosition) ([]domain.PortfolioPositionsWithAssetUid, error) {
	ret := _m.Called(ctx, portffolioPositions)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPositionsToPositionsWithAssetUid")
	}

	var r0 []domain.PortfolioPositionsWithAssetUid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.PortfolioPosition) ([]domain.PortfolioPositionsWithAssetUid, error)); ok {
		return rf(ctx, portffolioPositions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.PortfolioPosition) []domain.PortfolioPositionsWithAssetUid); ok {
		r0 = rf(ctx, portffolioPositions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PortfolioPositionsWithAssetUid)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.PortfolioPosition) error); ok {
		r1 = rf(ctx, portffolioPositions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPositionProcessor creates a new instance of PositionProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionProcessor {
	mock := &PositionProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
