// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReportLineBuilder is an autogenerated mock type for the ReportLineBuilder type
type ReportLineBuilder struct {
	mock.Mock
}

// CreateNewReportLines provides a mock function with given fields: ctx, position, operationsDb
func (_m *ReportLineBuilder) CreateNewReportLines(ctx context.Context, position domain.PortfolioPositionsWithAssetUid, operationsDb []domain.OperationWithoutCustomTypes) (*domain.ReportLine, error) {
	ret := _m.Called(ctx, position, operationsDb)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewReportLines")
	}

	var r0 *domain.ReportLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PortfolioPositionsWithAssetUid, []domain.OperationWithoutCustomTypes) (*domain.ReportLine, error)); ok {
		return rf(ctx, position, operationsDb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PortfolioPositionsWithAssetUid, []domain.OperationWithoutCustomTypes) *domain.ReportLine); ok {
		r0 = rf(ctx, position, operationsDb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReportLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PortfolioPositionsWithAssetUid, []domain.OperationWithoutCustomTypes) error); ok {
		r1 = rf(ctx, position, operationsDb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportLineBuilder creates a new instance of ReportLineBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportLineBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportLineBuilder {
	mock := &ReportLineBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
