// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	report "bonds-report-service/internal/domain/report_position"
)

// ReportProcessor is an autogenerated mock type for the ReportProcessor type
type ReportProcessor struct {
	mock.Mock
}

// ProcessOperations provides a mock function with given fields: ctx, reportLine
func (_m *ReportProcessor) ProcessOperations(ctx context.Context, reportLine *domain.ReportLine) (*report.ReportPositions, error) {
	ret := _m.Called(ctx, reportLine)

	if len(ret) == 0 {
		panic("no return value specified for ProcessOperations")
	}

	var r0 *report.ReportPositions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportLine) (*report.ReportPositions, error)); ok {
		return rf(ctx, reportLine)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportLine) *report.ReportPositions); ok {
		r0 = rf(ctx, reportLine)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*report.ReportPositions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ReportLine) error); ok {
		r1 = rf(ctx, reportLine)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportProcessor creates a new instance of ReportProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportProcessor {
	mock := &ReportProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
