// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TinkoffPortfolioClient is an autogenerated mock type for the TinkoffPortfolioClient type
type TinkoffPortfolioClient struct {
	mock.Mock
}

// GetAccounts provides a mock function with given fields: ctx
func (_m *TinkoffPortfolioClient) GetAccounts(ctx context.Context) (map[string]domain.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 map[string]domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]domain.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]domain.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperations provides a mock function with given fields: ctx, accountId, date
func (_m *TinkoffPortfolioClient) GetOperations(ctx context.Context, accountId string, date time.Time) ([]domain.Operation, error) {
	ret := _m.Called(ctx, accountId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetOperations")
	}

	var r0 []domain.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]domain.Operation, error)); ok {
		return rf(ctx, accountId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []domain.Operation); ok {
		r0 = rf(ctx, accountId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, accountId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortfolio provides a mock function with given fields: ctx, accountID, accountStatus
func (_m *TinkoffPortfolioClient) GetPortfolio(ctx context.Context, accountID string, accountStatus int64) (domain.Portfolio, error) {
	ret := _m.Called(ctx, accountID, accountStatus)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 domain.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (domain.Portfolio, error)); ok {
		return rf(ctx, accountID, accountStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) domain.Portfolio); ok {
		r0 = rf(ctx, accountID, accountStatus)
	} else {
		r0 = ret.Get(0).(domain.Portfolio)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, accountID, accountStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffPortfolioClient creates a new instance of TinkoffPortfolioClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffPortfolioClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffPortfolioClient {
	mock := &TinkoffPortfolioClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
