// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "telegram-mock/internal/service"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// SaveMessage provides a mock function with given fields: ctx, message
func (_m *Service) SaveMessage(ctx context.Context, message service.IncomingMessage) {
	_m.Called(ctx, message)
}

// Updates provides a mock function with given fields: ctx, offset, limit
func (_m *Service) Updates(ctx context.Context, offset int, limit int) []service.Update {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 []service.Update
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []service.Update); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Update)
		}
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
