// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	models "bonds-report-service/internal/models"

	url "net/url"
)

// TransportClient is an autogenerated mock type for the TransportClient type
type TransportClient struct {
	mock.Mock
}

// DoRequest provides a mock function with given fields: ctx, path, query, requestBody
func (_m *TransportClient) DoRequest(ctx context.Context, path string, query url.Values, requestBody io.Reader) (*models.HTTPResponse, error) {
	ret := _m.Called(ctx, path, query, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 *models.HTTPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values, io.Reader) (*models.HTTPResponse, error)); ok {
		return rf(ctx, path, query, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values, io.Reader) *models.HTTPResponse); ok {
		r0 = rf(ctx, path, query, requestBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.HTTPResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values, io.Reader) error); ok {
		r1 = rf(ctx, path, query, requestBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransportClient creates a new instance of TransportClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransportClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransportClient {
	mock := &TransportClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
