// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/models/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CbrClient is an autogenerated mock type for the CbrClient type
type CbrClient struct {
	mock.Mock
}

// GetAllCurrencies provides a mock function with given fields: ctx, date
func (_m *CbrClient) GetAllCurrencies(ctx context.Context, date time.Time) (domain.CurrenciesCBR, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCurrencies")
	}

	var r0 domain.CurrenciesCBR
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (domain.CurrenciesCBR, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) domain.CurrenciesCBR); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Get(0).(domain.CurrenciesCBR)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCbrClient creates a new instance of CbrClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCbrClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CbrClient {
	mock := &CbrClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
