// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/models/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TinkoffAnalyticsClient is an autogenerated mock type for the TinkoffAnalyticsClient type
type TinkoffAnalyticsClient struct {
	mock.Mock
}

// GetAllAssetUids provides a mock function with given fields: ctx
func (_m *TinkoffAnalyticsClient) GetAllAssetUids(ctx context.Context) (map[string]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetUids")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBondsActions provides a mock function with given fields: ctx, instrumentUid
func (_m *TinkoffAnalyticsClient) GetBondsActions(ctx context.Context, instrumentUid string) (domain.BondIdentIdentifiers, error) {
	ret := _m.Called(ctx, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetBondsActions")
	}

	var r0 domain.BondIdentIdentifiers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BondIdentIdentifiers, error)); ok {
		return rf(ctx, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BondIdentIdentifiers); ok {
		r0 = rf(ctx, instrumentUid)
	} else {
		r0 = ret.Get(0).(domain.BondIdentIdentifiers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastPriceInPersentageToNominal provides a mock function with given fields: ctx, instrumentUid
func (_m *TinkoffAnalyticsClient) GetLastPriceInPersentageToNominal(ctx context.Context, instrumentUid string) (domain.LastPrice, error) {
	ret := _m.Called(ctx, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetLastPriceInPersentageToNominal")
	}

	var r0 domain.LastPrice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.LastPrice, error)); ok {
		return rf(ctx, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.LastPrice); ok {
		r0 = rf(ctx, instrumentUid)
	} else {
		r0 = ret.Get(0).(domain.LastPrice)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffAnalyticsClient creates a new instance of TinkoffAnalyticsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffAnalyticsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffAnalyticsClient {
	mock := &TinkoffAnalyticsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
