// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/models/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TinkoffInstrumentsClient is an autogenerated mock type for the TinkoffInstrumentsClient type
type TinkoffInstrumentsClient struct {
	mock.Mock
}

// FindBy provides a mock function with given fields: ctx, query
func (_m *TinkoffInstrumentsClient) FindBy(ctx context.Context, query string) ([]domain.InstrumentShort, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for FindBy")
	}

	var r0 []domain.InstrumentShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.InstrumentShort, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.InstrumentShort); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InstrumentShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBondByUid provides a mock function with given fields: ctx, uid
func (_m *TinkoffInstrumentsClient) GetBondByUid(ctx context.Context, uid string) (domain.Bond, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetBondByUid")
	}

	var r0 domain.Bond
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Bond, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Bond); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(domain.Bond)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrencyBy provides a mock function with given fields: ctx, figi
func (_m *TinkoffInstrumentsClient) GetCurrencyBy(ctx context.Context, figi string) (domain.Currency, error) {
	ret := _m.Called(ctx, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyBy")
	}

	var r0 domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Currency, error)); ok {
		return rf(ctx, figi)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Currency); ok {
		r0 = rf(ctx, figi)
	} else {
		r0 = ret.Get(0).(domain.Currency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFutureBy provides a mock function with given fields: ctx, figi
func (_m *TinkoffInstrumentsClient) GetFutureBy(ctx context.Context, figi string) (domain.Future, error) {
	ret := _m.Called(ctx, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetFutureBy")
	}

	var r0 domain.Future
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Future, error)); ok {
		return rf(ctx, figi)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Future); ok {
		r0 = rf(ctx, figi)
	} else {
		r0 = ret.Get(0).(domain.Future)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShareCurrencyBy provides a mock function with given fields: ctx, figi
func (_m *TinkoffInstrumentsClient) GetShareCurrencyBy(ctx context.Context, figi string) (domain.ShareCurrency, error) {
	ret := _m.Called(ctx, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetShareCurrencyBy")
	}

	var r0 domain.ShareCurrency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ShareCurrency, error)); ok {
		return rf(ctx, figi)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ShareCurrency); ok {
		r0 = rf(ctx, figi)
	} else {
		r0 = ret.Get(0).(domain.ShareCurrency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffInstrumentsClient creates a new instance of TinkoffInstrumentsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffInstrumentsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffInstrumentsClient {
	mock := &TinkoffInstrumentsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
