// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "cbr/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CurrencyService is an autogenerated mock type for the CurrencyService type
type CurrencyService struct {
	mock.Mock
}

// GetAllCurrencies provides a mock function with given fields: ctx, date
func (_m *CurrencyService) GetAllCurrencies(ctx context.Context, date time.Time) (models.CurrenciesResponce, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCurrencies")
	}

	var r0 models.CurrenciesResponce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (models.CurrenciesResponce, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) models.CurrenciesResponce); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Get(0).(models.CurrenciesResponce)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCurrencyService creates a new instance of CurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyService {
	mock := &CurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
