// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "cbr/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

// GetAllCurrencies provides a mock function with given fields: formatDate
func (_m *HTTPClient) GetAllCurrencies(formatDate string) (service.CurrenciesResponce, error) {
	ret := _m.Called(formatDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCurrencies")
	}

	var r0 service.CurrenciesResponce
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.CurrenciesResponce, error)); ok {
		return rf(formatDate)
	}
	if rf, ok := ret.Get(0).(func(string) service.CurrenciesResponce); ok {
		r0 = rf(formatDate)
	} else {
		r0 = ret.Get(0).(service.CurrenciesResponce)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(formatDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHTTPClient creates a new instance of HTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPClient {
	mock := &HTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
