// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	investgo "github.com/russianinvestments/invest-api-go-sdk/investgo"
	mock "github.com/stretchr/testify/mock"

	service "tinkoffApi/internal/service"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

// GetAllAssetUids provides a mock function with given fields: client
func (_m *AnalyticsService) GetAllAssetUids(client *investgo.Client) (map[string]string, error) {
	ret := _m.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetUids")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client) (map[string]string, error)); ok {
		return rf(client)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client) map[string]string); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBondsActions provides a mock function with given fields: client, instrumentUid
func (_m *AnalyticsService) GetBondsActions(client *investgo.Client, instrumentUid string) (service.BondIdentIdentifiers, error) {
	ret := _m.Called(client, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetBondsActions")
	}

	var r0 service.BondIdentIdentifiers
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) (service.BondIdentIdentifiers, error)); ok {
		return rf(client, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) service.BondIdentIdentifiers); ok {
		r0 = rf(client, instrumentUid)
	} else {
		r0 = ret.Get(0).(service.BondIdentIdentifiers)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClient provides a mock function with given fields: ctx
func (_m *AnalyticsService) GetClient(ctx context.Context) (*investgo.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *investgo.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*investgo.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *investgo.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investgo.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastPriceInPersentageToNominal provides a mock function with given fields: client, instrumentUid
func (_m *AnalyticsService) GetLastPriceInPersentageToNominal(client *investgo.Client, instrumentUid string) (service.LastPriceResponse, error) {
	ret := _m.Called(client, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetLastPriceInPersentageToNominal")
	}

	var r0 service.LastPriceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) (service.LastPriceResponse, error)); ok {
		return rf(client, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) service.LastPriceResponse); ok {
		r0 = rf(client, instrumentUid)
	} else {
		r0 = ret.Get(0).(service.LastPriceResponse)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
