// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	service "tinkoffApi/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

// GetAllAssetUids provides a mock function with no fields
func (_m *AnalyticsService) GetAllAssetUids() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetUids")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBondsActions provides a mock function with given fields: instrumentUid
func (_m *AnalyticsService) GetBondsActions(instrumentUid string) (service.BondIdentIdentifiers, error) {
	ret := _m.Called(instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetBondsActions")
	}

	var r0 service.BondIdentIdentifiers
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.BondIdentIdentifiers, error)); ok {
		return rf(instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(string) service.BondIdentIdentifiers); ok {
		r0 = rf(instrumentUid)
	} else {
		r0 = ret.Get(0).(service.BondIdentIdentifiers)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClient provides a mock function with given fields: ctx, token
func (_m *AnalyticsService) GetClient(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastPriceInPersentageToNominal provides a mock function with given fields: instrumentUid
func (_m *AnalyticsService) GetLastPriceInPersentageToNominal(instrumentUid string) (service.LastPriceResponse, error) {
	ret := _m.Called(instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for GetLastPriceInPersentageToNominal")
	}

	var r0 service.LastPriceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.LastPriceResponse, error)); ok {
		return rf(instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(string) service.LastPriceResponse); ok {
		r0 = rf(instrumentUid)
	} else {
		r0 = ret.Get(0).(service.LastPriceResponse)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
