// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	investgo "github.com/russianinvestments/invest-api-go-sdk/investgo"
	mock "github.com/stretchr/testify/mock"

	service "tinkoffApi/internal/service"
)

// InstrumentService is an autogenerated mock type for the InstrumentService type
type InstrumentService struct {
	mock.Mock
}

// FindBy provides a mock function with given fields: client, query
func (_m *InstrumentService) FindBy(client *investgo.Client, query string) ([]service.InstrumentShort, error) {
	ret := _m.Called(client, query)

	if len(ret) == 0 {
		panic("no return value specified for FindBy")
	}

	var r0 []service.InstrumentShort
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) ([]service.InstrumentShort, error)); ok {
		return rf(client, query)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) []service.InstrumentShort); ok {
		r0 = rf(client, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.InstrumentShort)
		}
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBondByUid provides a mock function with given fields: client, uid
func (_m *InstrumentService) GetBondByUid(client *investgo.Client, uid string) (service.Bond, error) {
	ret := _m.Called(client, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetBondByUid")
	}

	var r0 service.Bond
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) (service.Bond, error)); ok {
		return rf(client, uid)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) service.Bond); ok {
		r0 = rf(client, uid)
	} else {
		r0 = ret.Get(0).(service.Bond)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClient provides a mock function with given fields: ctx
func (_m *InstrumentService) GetClient(ctx context.Context) (*investgo.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *investgo.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*investgo.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *investgo.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investgo.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrencyBy provides a mock function with given fields: client, figi
func (_m *InstrumentService) GetCurrencyBy(client *investgo.Client, figi string) (service.Currency, error) {
	ret := _m.Called(client, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyBy")
	}

	var r0 service.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) (service.Currency, error)); ok {
		return rf(client, figi)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) service.Currency); ok {
		r0 = rf(client, figi)
	} else {
		r0 = ret.Get(0).(service.Currency)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFutureBy provides a mock function with given fields: client, figi
func (_m *InstrumentService) GetFutureBy(client *investgo.Client, figi string) (service.Future, error) {
	ret := _m.Called(client, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetFutureBy")
	}

	var r0 service.Future
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) (service.Future, error)); ok {
		return rf(client, figi)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) service.Future); ok {
		r0 = rf(client, figi)
	} else {
		r0 = ret.Get(0).(service.Future)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShareCurrencyBy provides a mock function with given fields: client, figi
func (_m *InstrumentService) GetShareCurrencyBy(client *investgo.Client, figi string) (service.ShareCurrencyByResponse, error) {
	ret := _m.Called(client, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetShareCurrencyBy")
	}

	var r0 service.ShareCurrencyByResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) (service.ShareCurrencyByResponse, error)); ok {
		return rf(client, figi)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, string) service.ShareCurrencyByResponse); ok {
		r0 = rf(client, figi)
	} else {
		r0 = ret.Get(0).(service.ShareCurrencyByResponse)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, string) error); ok {
		r1 = rf(client, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInstrumentService creates a new instance of InstrumentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstrumentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstrumentService {
	mock := &InstrumentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
