// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	investgo "github.com/russianinvestments/invest-api-go-sdk/investgo"
	mock "github.com/stretchr/testify/mock"

	service "tinkoffApi/internal/service"
)

// PortfolioService is an autogenerated mock type for the PortfolioService type
type PortfolioService struct {
	mock.Mock
}

// GetAccounts provides a mock function with given fields: client
func (_m *PortfolioService) GetAccounts(client *investgo.Client) (map[string]service.Account, error) {
	ret := _m.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 map[string]service.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client) (map[string]service.Account, error)); ok {
		return rf(client)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client) map[string]service.Account); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]service.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClient provides a mock function with given fields: ctx
func (_m *PortfolioService) GetClient(ctx context.Context) (*investgo.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *investgo.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*investgo.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *investgo.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investgo.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperations provides a mock function with given fields: client, request
func (_m *PortfolioService) GetOperations(client *investgo.Client, request service.OperationsRequest) ([]service.Operation, error) {
	ret := _m.Called(client, request)

	if len(ret) == 0 {
		panic("no return value specified for GetOperations")
	}

	var r0 []service.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, service.OperationsRequest) ([]service.Operation, error)); ok {
		return rf(client, request)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, service.OperationsRequest) []service.Operation); ok {
		r0 = rf(client, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, service.OperationsRequest) error); ok {
		r1 = rf(client, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortfolio provides a mock function with given fields: client, request
func (_m *PortfolioService) GetPortfolio(client *investgo.Client, request service.PortfolioRequest) (service.Portfolio, error) {
	ret := _m.Called(client, request)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 service.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, service.PortfolioRequest) (service.Portfolio, error)); ok {
		return rf(client, request)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, service.PortfolioRequest) service.Portfolio); ok {
		r0 = rf(client, request)
	} else {
		r0 = ret.Get(0).(service.Portfolio)
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, service.PortfolioRequest) error); ok {
		r1 = rf(client, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeSafeGetOperationsRequest provides a mock function with given fields: client, request
func (_m *PortfolioService) MakeSafeGetOperationsRequest(client *investgo.Client, request service.OperationsRequest) ([]service.Operation, error) {
	ret := _m.Called(client, request)

	if len(ret) == 0 {
		panic("no return value specified for MakeSafeGetOperationsRequest")
	}

	var r0 []service.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(*investgo.Client, service.OperationsRequest) ([]service.Operation, error)); ok {
		return rf(client, request)
	}
	if rf, ok := ret.Get(0).(func(*investgo.Client, service.OperationsRequest) []service.Operation); ok {
		r0 = rf(client, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(*investgo.Client, service.OperationsRequest) error); ok {
		r1 = rf(client, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPortfolioService creates a new instance of PortfolioService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioService {
	mock := &PortfolioService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
