// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "cbr/internal/service"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

// GetAllCurrencies provides a mock function with given fields: date
func (_m *HTTPClient) GetAllCurrencies(date time.Time) (service.ValCurs, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCurrencies")
	}

	var r0 service.ValCurs
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) (service.ValCurs, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) service.ValCurs); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Get(0).(service.ValCurs)
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHTTPClient creates a new instance of HTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPClient {
	mock := &HTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
