// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "moex/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ServiceClient is an autogenerated mock type for the ServiceClient type
type ServiceClient struct {
	mock.Mock
}

// GetSpecifications provides a mock function with given fields: ctx, req
func (_m *ServiceClient) GetSpecifications(ctx context.Context, req models.SpecificationsRequest) (models.Values, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecifications")
	}

	var r0 models.Values
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SpecificationsRequest) (models.Values, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.SpecificationsRequest) models.Values); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.Values)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.SpecificationsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceClient creates a new instance of ServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceClient {
	mock := &ServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
