// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "main/internal/service"

	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetSpecifications provides a mock function with given fields: req
func (_m *Service) GetSpecifications(req service.SpecificationsRequest) (service.Values, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecifications")
	}

	var r0 service.Values
	var r1 error
	if rf, ok := ret.Get(0).(func(service.SpecificationsRequest) (service.Values, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(service.SpecificationsRequest) service.Values); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(service.Values)
	}

	if rf, ok := ret.Get(1).(func(service.SpecificationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoRequest provides a mock function with given fields: Path, query
func (_m *Service) DoRequest(Path string, query url.Values) ([]byte, error) {
	ret := _m.Called(Path, query)

	if len(ret) == 0 {
		panic("no return value specified for doRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, url.Values) ([]byte, error)); ok {
		return rf(Path, query)
	}
	if rf, ok := ret.Get(0).(func(string, url.Values) []byte); ok {
		r0 = rf(Path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, url.Values) error); ok {
		r1 = rf(Path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
