// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	service "tinkoffApi/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// InstrumentService is an autogenerated mock type for the InstrumentService type
type InstrumentService struct {
	mock.Mock
}

// FindBy provides a mock function with given fields: query
func (_m *InstrumentService) FindBy(query string) ([]service.InstrumentShort, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FindBy")
	}

	var r0 []service.InstrumentShort
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]service.InstrumentShort, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []service.InstrumentShort); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.InstrumentShort)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBondByUid provides a mock function with given fields: uid
func (_m *InstrumentService) GetBondByUid(uid string) (service.Bond, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetBondByUid")
	}

	var r0 service.Bond
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.Bond, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) service.Bond); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Get(0).(service.Bond)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClient provides a mock function with given fields: ctx, token
func (_m *InstrumentService) GetClient(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrencyBy provides a mock function with given fields: figi
func (_m *InstrumentService) GetCurrencyBy(figi string) (service.Currency, error) {
	ret := _m.Called(figi)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyBy")
	}

	var r0 service.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.Currency, error)); ok {
		return rf(figi)
	}
	if rf, ok := ret.Get(0).(func(string) service.Currency); ok {
		r0 = rf(figi)
	} else {
		r0 = ret.Get(0).(service.Currency)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFutureBy provides a mock function with given fields: figi
func (_m *InstrumentService) GetFutureBy(figi string) (service.Future, error) {
	ret := _m.Called(figi)

	if len(ret) == 0 {
		panic("no return value specified for GetFutureBy")
	}

	var r0 service.Future
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.Future, error)); ok {
		return rf(figi)
	}
	if rf, ok := ret.Get(0).(func(string) service.Future); ok {
		r0 = rf(figi)
	} else {
		r0 = ret.Get(0).(service.Future)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShareCurrencyBy provides a mock function with given fields: figi
func (_m *InstrumentService) GetShareCurrencyBy(figi string) (service.ShareCurrencyByResponse, error) {
	ret := _m.Called(figi)

	if len(ret) == 0 {
		panic("no return value specified for GetShareCurrencyBy")
	}

	var r0 service.ShareCurrencyByResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (service.ShareCurrencyByResponse, error)); ok {
		return rf(figi)
	}
	if rf, ok := ret.Get(0).(func(string) service.ShareCurrencyByResponse); ok {
		r0 = rf(figi)
	} else {
		r0 = ret.Get(0).(service.ShareCurrencyByResponse)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInstrumentService creates a new instance of InstrumentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstrumentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstrumentService {
	mock := &InstrumentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
