// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "tinkoffApi/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// PortfolioService is an autogenerated mock type for the PortfolioService type
type PortfolioService struct {
	mock.Mock
}

// GetAccounts provides a mock function with no fields
func (_m *PortfolioService) GetAccounts() (map[string]service.Account, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 map[string]service.Account
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]service.Account, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]service.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]service.Account)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperations provides a mock function with given fields: request
func (_m *PortfolioService) GetOperations(request service.OperationsRequest) ([]service.Operation, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for GetOperations")
	}

	var r0 []service.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(service.OperationsRequest) ([]service.Operation, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(service.OperationsRequest) []service.Operation); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(service.OperationsRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortfolio provides a mock function with given fields: request
func (_m *PortfolioService) GetPortfolio(request service.PortfolioRequest) (service.Portfolio, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 service.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(service.PortfolioRequest) (service.Portfolio, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(service.PortfolioRequest) service.Portfolio); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(service.Portfolio)
	}

	if rf, ok := ret.Get(1).(func(service.PortfolioRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeSafeGetOperationsRequest provides a mock function with given fields: request
func (_m *PortfolioService) MakeSafeGetOperationsRequest(request service.OperationsRequest) ([]service.Operation, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for MakeSafeGetOperationsRequest")
	}

	var r0 []service.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(service.OperationsRequest) ([]service.Operation, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(service.OperationsRequest) []service.Operation); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(service.OperationsRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPortfolioService creates a new instance of PortfolioService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortfolioService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortfolioService {
	mock := &PortfolioService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
